name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build libpq
        run: bazel build //:libpq
      - name: Test C program
        run: |
            docker run --rm -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:16.2-alpine &&
                while !</dev/tcp/127.0.0.1/5432; do sleep 1; done &&
                bazel build //examples/c:main &&
                ./bazel-bin/main
